apiVersion: project.openshift.io/v1
kind: Project
metadata:
  labels:
    kubernetes.io/metadata.name: ${TEMPO_STACK_NAMESPACE}
  name: ${TEMPO_STACK_NAMESPACE}
---
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  labels:
    app.kubernetes.io/managed-by: tempo-operator
    tempo.grafana.com/distribution: openshift
  name: ${TEMPO_STACK_NAME}
  namespace: ${TEMPO_STACK_NAMESPACE}
spec:
  limits:
    global:
      query:
        maxSearchDuration: 0s
  managementState: Managed
  observability:
    metrics:
      createPrometheusRules: true
      createServiceMonitors: true
    tracing:
      jaeger_agent_endpoint: localhost:6831
      otlp_http_endpoint: http://localhost:4320 # Puerto por defecto en la implementaci贸n de TempoStack
  replicationFactor: 1
  resources:
    total:
      limits:
        cpu: "2"
        memory: 2Gi
  retention:
    global:
      traces: 48h0m0s # Valor acorde a necesidades particulares
  search:
    defaultResultLimit: 20
    maxDuration: 0s
  serviceAccount: tempo-${TEMPO_STACK_NAME}
  storage:
    secret:
      name: ${TEMPO_STACK_NAME}-storage-secret
      type: s3
    tls:
      enabled: false
  storageSize: ${TEMPO_STACK_STORAGE_SIZE}
  template:
    compactor:
      replicas: 1
    distributor:
      component:
        replicas: 1
      tls:
        enabled: false #Si se desactiva en TempoStack, debe estar desactivado el TLS en el OpenTelemetryCollector
    gateway:
      component:
        replicas: 1
      enabled: true
      ingress:
        route:
          termination: reencrypt
        type: route
      rbac:
        enabled: false
    ingester:
      replicas: 1
    querier:
      replicas: 1
    queryFrontend:
      component:
        replicas: 1
        resources: # Recomendado para mantenimiento de QueryFrontend 
          limits:
            cpu: "3"
            memory: 5Gi
      jaegerQuery:
        enabled: true
        monitorTab:
          enabled: false
          prometheusEndpoint: ""
        servicesQueryDuration: 72h0m0s
  tenants: # Configuraci贸n de tenants para TempoStack. Para implementaci贸n deben establecerse dos, acorde a la documentaci贸n del operador en RedHat
    authentication:
    - tenantId: ${TEMPO_TENANT_NAME}-0
      tenantName: ${TEMPO_TENANT_NAME}-0 # El valor del tenant en TempoStack es arbitrario. Debe coincidir con el nombre del tenant en el OpenTelemetryCollector
    - tenantId: ${TEMPO_TENANT_NAME}-1
      tenantName: ${TEMPO_TENANT_NAME}-1
    mode: openshift
  timeout: 30s
