apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: ${OTEL_COLLECTOR_NAME}
  namespace: ${TEMPO_STACK_NAMESPACE}
spec:
  config:
    exporters:
      otlp:
        auth:
          authenticator: bearertokenauth
        endpoint: tempo-${TEMPO_STACK_NAME}-gateway.${TEMPO_STACK_NAMESPACE}.svc.cluster.local:8090
        headers:
          X-Scope-OrgID: prod
        tls:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          insecure: false
    extensions:
      bearertokenauth:
        filename: /var/run/secrets/kubernetes.io/serviceaccount/token
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_binary:
            endpoint: 0.0.0.0:6832
          thrift_compact:
            endpoint: 0.0.0.0:6831
          thrift_http:
            endpoint: 0.0.0.0:14268
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      extensions:
      - bearertokenauth # Activar las extensiones acorde a los plugins que requieran activarse. 
      pipelines:
        traces:
          exporters: # Deben coincidir con los exporters definidos arriba
          - otlp
          - debug # Para depuración, se puede eliminar en producción
          receivers: # Deben coincidir con los receivers definidos arriba
          - otlp
          - jaeger
      telemetry:
        metrics:
          readers:
          - pull:
              exporter:
                prometheus:
                  host: 0.0.0.0
                  port: 8888
  configVersions: 3
  ipFamilyPolicy: SingleStack
  managementState: managed
  mode: deployment
  replicas: 1
  serviceAccount: otel-collector # Debe coincidir con el ServiceAccount creado en el archivo de permisos de cluster
  targetAllocator:
    allocationStrategy: consistent-hashing
    collectorNotReadyGracePeriod: 30s
    filterStrategy: relabel-config
    prometheusCR:
      scrapeInterval: 30s
  upgradeStrategy: automatic