# Se compila lo recomendado en la KB https://access.redhat.com/articles/7091540 para la prueba del Collector de OpenTelemetry con TempoStack
---
# Usar este Job para generar trazas de prueba en TempoStack para el protocolo gRPC.
apiVersion: batch/v1
kind: Job
metadata:
 name: generate-traces-grpc
 namespace: <namespace-name>
spec:
 template:
   spec:
     containers:
     - name: telemetrygen
       image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.92.0
       args:
       - traces
       - --otlp-endpoint=${OTEL_COLLECTOR_NAME}.${TEMPO_STACK_NAMESPACE}.svc:4317
       - --service=grpc
       - --otlp-insecure
       - --traces=10
     restartPolicy: Never
---
# Usar este Job para generar trazas de prueba en TempoStack para el protocolo HTTP.
apiVersion: batch/v1
kind: Job
metadata:
 name: generate-traces-http
 namespace: <namespace-name>
spec:
 template:
   spec:
     containers:
       - name: telemetrygen
         image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.92.0
         args:
           - traces
           - --otlp-endpoint=${OTEL_COLLECTOR_NAME}.${TEMPO_STACK_NAMESPACE}.svc:4318
           - --otlp-http
           - --otlp-insecure
           - --service=http
           - --traces=10
     restartPolicy: Never
